# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportGenere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("academique", "Rapport académique"),
                            ("administratif", "Rapport administratif"),
                            ("financier", "Rapport financier"),
                            ("statistiques_classe", "Statistiques par classe"),
                            ("autre", "Autre"),
                        ],
                        max_length=25,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "format_export",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "parametres",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtres utilisés (classe, période, dates...)",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="reporting/rapports/"
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="core.etablissement",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport généré",
                "verbose_name_plural": "Rapports générés",
                "ordering": ["-created_at"],
            },
        ),
    ]
