# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=200)),
                ("contenu", models.TextField()),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True, null=True, upload_to="communication/pieces_jointes/"
                    ),
                ),
                ("lu", models.BooleanField(default=False)),
                ("lu_le", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("interne", "Notification interne"),
                        ],
                        default="interne",
                        max_length=10,
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("resultat", "Résultat scolaire"),
                            ("absence", "Absence"),
                            ("convocation", "Convocation"),
                            ("paiement", "Paiement"),
                            ("annonce", "Annonce"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=15,
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200)),
                ("contenu", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("envoyee", "Envoyée"),
                            ("echec", "Échec"),
                        ],
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("lu", models.BooleanField(default=False)),
                ("envoyee_le", models.DateTimeField(blank=True, null=True)),
                ("erreur", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                (
                    "public_cible",
                    models.CharField(
                        choices=[
                            ("tous", "Tout le monde"),
                            ("enseignants", "Enseignants"),
                            ("eleves", "Élèves"),
                            ("parents", "Parents"),
                            ("classe", "Une classe spécifique"),
                        ],
                        default="tous",
                        max_length=15,
                    ),
                ),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True, null=True, upload_to="communication/annonces/"
                    ),
                ),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                ("epinglee", models.BooleanField(default=False)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annonces_publiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-epinglee", "-date_publication"],
            },
        ),
    ]
