# Generated by Django 5.2.17 on 2026-10-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('resultat', 'Résultat scolaire'), ('absence', 'Absence'), ('convocation', 'Convocation'), ('paiement', 'Paiement'), ('annonce', 'Annonce'), ('message', 'Message'), ('autre', 'Autre')], default='autre', max_length=15),
        ),
    ]
