# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "type_employe",
                    models.CharField(
                        choices=[
                            ("enseignant", "Enseignant"),
                            ("administratif", "Personnel administratif"),
                            ("surveillant", "Surveillant"),
                            ("technique", "Personnel technique/entretien"),
                            ("autre", "Autre"),
                        ],
                        default="enseignant",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("lieu_naissance", models.CharField(blank=True, max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email_personnel", models.EmailField(blank=True, max_length=254)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employes/photos/"
                    ),
                ),
                ("diplome", models.CharField(blank=True, max_length=150)),
                ("specialite", models.CharField(blank=True, max_length=150)),
                ("date_embauche", models.DateField(blank=True, null=True)),
                ("date_fin_contrat", models.DateField(blank=True, null=True)),
                (
                    "type_contrat",
                    models.CharField(
                        blank=True, help_text="CDI, CDD, Vacataire, ...", max_length=50
                    ),
                ),
                ("numero_cnss", models.CharField(blank=True, max_length=50)),
                ("iban_ou_compte", models.CharField(blank=True, max_length=100)),
                ("actif", models.BooleanField(default=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employes",
                        to="core.etablissement",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_employe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "employe_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="staff.employe",
                    ),
                ),
                (
                    "grade_academique",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Professeur certifié, Instituteur",
                        max_length=100,
                    ),
                ),
                (
                    "matieres_enseignees",
                    models.ManyToManyField(
                        blank=True, related_name="enseignants", to="core.matiere"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Enseignants",
            },
            bases=("staff.employe",),
        ),
        migrations.CreateModel(
            name="DocumentPedagogique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=200)),
                ("fichier", models.FileField(upload_to="pedagogie/documents/")),
                ("description", models.TextField(blank=True)),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_pedagogiques",
                        to="core.classe",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_pedagogiques",
                        to="core.matiere",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_pedagogiques",
                        to="staff.enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document pédagogique",
                "verbose_name_plural": "Documents pédagogiques",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresenceEmploye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("retard", "Retard"),
                            ("conge", "Congé"),
                            ("mission", "Mission"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("justifie", models.BooleanField(default=False)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="staff.employe",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence employé",
                "verbose_name_plural": "Présences employés",
                "ordering": ["-date"],
                "unique_together": {("employe", "date")},
            },
        ),
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "volume_horaire_hebdo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("date_debut", models.DateField(auto_now_add=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.anneescolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.classe",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.matiere",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="staff.enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation",
                "verbose_name_plural": "Affectations",
                "unique_together": {
                    ("enseignant", "classe", "matiere", "annee_scolaire")
                },
            },
        ),
    ]
