# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(help_text="Ex: 2025-2026", max_length=20)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_courante", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="CreneauEmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jour",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("salle", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Créneau d'emploi du temps",
                "verbose_name_plural": "Emplois du temps",
                "ordering": ["jour", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200)),
                (
                    "sigle",
                    models.CharField(
                        help_text="Code court utilisé dans les matricules",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "type_etablissement",
                    models.CharField(
                        choices=[
                            ("prescolaire", "Préscolaire"),
                            ("primaire", "Primaire"),
                            ("secondaire", "Secondaire"),
                            ("mixte", "Mixte (plusieurs cycles)"),
                        ],
                        default="mixte",
                        max_length=20,
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("pays", models.CharField(default="Mali", max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="etablissements/logos/"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        help_text="Slogan / devise de l'établissement",
                        max_length=255,
                    ),
                ),
                ("directeur_nom", models.CharField(blank=True, max_length=150)),
                (
                    "directeur_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="etablissements/signatures/"
                    ),
                ),
                (
                    "cachet",
                    models.ImageField(
                        blank=True, null=True, upload_to="etablissements/cachets/"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="JournalActivite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("export", "Export"),
                            ("payment", "Paiement"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modele",
                    models.CharField(
                        blank=True, help_text="Nom du modèle concerné", max_length=100
                    ),
                ),
                ("objet_id", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entrée du journal d'activité",
                "verbose_name_plural": "Journal d'activité",
                "ordering": ["-horodatage"],
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "coefficient_defaut",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: 6e, Terminale, CP1, Grande Section",
                        max_length=100,
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("prescolaire", "Préscolaire"),
                            ("primaire", "Primaire"),
                            ("secondaire_1", "Secondaire 1er cycle"),
                            ("secondaire_2", "Secondaire 2nd cycle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ordre d'affichage / progression"
                    ),
                ),
            ],
            options={
                "ordering": ["etablissement", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="Periode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_periode",
                    models.CharField(
                        choices=[("trimestre", "Trimestre"), ("semestre", "Semestre")],
                        default="trimestre",
                        max_length=10,
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2 ou 3 (trimestre) / 1, 2 (semestre)"
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=50)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("est_courante", models.BooleanField(default=False)),
                ("cloturee", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["annee_scolaire", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: TSE, TSECO, Lettres", max_length=100
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: 6e A, Terminale TSE B", max_length=50
                    ),
                ),
                ("effectif_max", models.PositiveIntegerField(default=50)),
                ("salle", models.CharField(blank=True, max_length=50)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="core.anneescolaire",
                    ),
                ),
            ],
            options={
                "ordering": ["niveau__ordre", "nom"],
            },
        ),
    ]
