# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="professeur_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_principales",
                to="staff.enseignant",
            ),
        ),
        migrations.AddField(
            model_name="creneauemploidutemps",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creneaux",
                to="core.classe",
            ),
        ),
        migrations.AddField(
            model_name="creneauemploidutemps",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creneaux",
                to="staff.enseignant",
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="anneescolaire",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annees_scolaires",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="journalactivite",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="journalactivite",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_journal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="creneauemploidutemps",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creneaux",
                to="core.matiere",
            ),
        ),
        migrations.AddField(
            model_name="niveau",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveaux",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.niveau",
            ),
        ),
        migrations.AddField(
            model_name="periode",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodes",
                to="core.anneescolaire",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="core.niveau",
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="serie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="core.serie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="anneescolaire",
            unique_together={("etablissement", "libelle")},
        ),
        migrations.AlterUniqueTogether(
            name="matiere",
            unique_together={("etablissement", "nom")},
        ),
        migrations.AlterUniqueTogether(
            name="niveau",
            unique_together={("etablissement", "nom")},
        ),
        migrations.AlterUniqueTogether(
            name="periode",
            unique_together={("annee_scolaire", "type_periode", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="serie",
            unique_together={("niveau", "nom")},
        ),
        migrations.AlterUniqueTogether(
            name="classe",
            unique_together={("annee_scolaire", "niveau", "nom")},
        ),
    ]
