# Generated by Django 5.2.17 on 2026-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='arrete_creation',
            field=models.CharField(blank=True, help_text='Ex: N° 10-2235/MEALN-SG du 21/07/2010', max_length=100),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='arrete_ouverture',
            field=models.CharField(blank=True, help_text='Ex: N° 2011-4993/MEALN-SG du 07/12/2011', max_length=100),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='directeur_titre',
            field=models.CharField(blank=True, default='Le Directeur', help_text='Ex: Le Proviseur, Le Directeur...', max_length=50),
        ),
    ]
