# Generated by Django 5.2.17 on 2026-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_etablissement_arrete_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='academie',
            field=models.CharField(blank=True, help_text="Ex: Académie d'Enseignement de Bamako Rive Droite", max_length=150),
        ),
    ]
