# Generated by Django 5.2.17 on 2026-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etablissement_academie'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='cap',
            field=models.CharField(blank=True, help_text="Centre d'Animation Pédagogique de rattachement (primaire/collège), si applicable", max_length=150, verbose_name='CAP'),
        ),
    ]
