# Generated by Django 5.2.17 on 2026-10-05 22:26

import django.db.models.deletion
from django.db import migrations, models


def copier_images_existantes(apps, schema_editor):
    """Copie en base les logos / cachets / signatures déjà présents sur le disque."""
    Etablissement = apps.get_model("core", "Etablissement")
    ImageEtablissement = apps.get_model("core", "ImageEtablissement")
    for etab in Etablissement.objects.all():
        for champ in ("logo", "cachet", "directeur_signature"):
            fichier = getattr(etab, champ)
            if not fichier:
                continue
            try:
                fichier.open("rb")
                contenu = fichier.read()
                fichier.close()
            except (OSError, ValueError):
                continue  # fichier déjà perdu (ex. redéploiement Render) : à renvoyer depuis l'application
            ImageEtablissement.objects.update_or_create(
                etablissement=etab, champ=champ, defaults={"nom_fichier": fichier.name, "contenu": contenu},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etablissement_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=30)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('contenu', models.BinaryField()),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_stockees', to='core.etablissement')),
            ],
            options={
                'verbose_name': "Image d'établissement (copie)",
                'verbose_name_plural': "Images d'établissement (copies)",
                'unique_together': {('etablissement', 'champ')},
            },
        ),
        migrations.RunPython(copier_images_existantes, migrations.RunPython.noop),
    ]
