# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "montant_rembourse",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("date_demande", models.DateField(auto_now_add=True)),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("nb_mensualites", models.PositiveSmallIntegerField(default=1)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours de remboursement"),
                            ("remboursee", "Remboursée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_cours",
                        max_length=12,
                    ),
                ),
                (
                    "approuve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avances",
                        to="staff.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avance sur salaire",
                "verbose_name_plural": "Avances sur salaire",
            },
        ),
        migrations.CreateModel(
            name="BulletinPaie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mois", models.PositiveSmallIntegerField()),
                ("annee", models.PositiveSmallIntegerField()),
                ("salaire_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_primes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_indemnites",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_heures_sup",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_retenues",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avances_deduites",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "salaire_brut",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_a_payer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validé"),
                            ("paye", "Payé"),
                        ],
                        default="brouillon",
                        max_length=10,
                    ),
                ),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="paie/bulletins/"
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins_paie",
                        to="staff.employe",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin de paie",
                "verbose_name_plural": "Bulletins de paie",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("employe", "mois", "annee")},
            },
        ),
        migrations.CreateModel(
            name="ContratSalaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("salaire_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "taux_horaire_supplementaire",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_effet", models.DateField(auto_now_add=True)),
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrat_salaire",
                        to="staff.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat de salaire",
                "verbose_name_plural": "Contrats de salaire",
            },
        ),
        migrations.CreateModel(
            name="ElementSalaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("prime", "Prime"),
                            ("indemnite", "Indemnité"),
                            ("retenue", "Retenue"),
                            ("heure_sup", "Heures supplémentaires"),
                        ],
                        max_length=12,
                    ),
                ),
                ("imposable", models.BooleanField(default=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements_salaire",
                        to="core.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de salaire",
                "verbose_name_plural": "Éléments de salaire",
                "unique_together": {("etablissement", "nom")},
            },
        ),
        migrations.CreateModel(
            name="LigneBulletinPaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "bulletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="payroll.bulletinpaie",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="payroll.elementsalaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de bulletin de paie",
                "verbose_name_plural": "Lignes de bulletin de paie",
            },
        ),
    ]
