# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_bourse",
                    models.CharField(
                        choices=[
                            ("bourse_totale", "Bourse totale"),
                            ("bourse_partielle", "Bourse partielle"),
                            ("reduction_fratrie", "Réduction fratrie"),
                            ("reduction_merite", "Réduction au mérite"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pourcentage_reduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% de réduction sur les frais",
                        max_digits=5,
                    ),
                ),
                (
                    "montant_fixe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alternative : montant fixe de réduction",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("motif", models.TextField(blank=True)),
                ("date_octroi", models.DateField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "approuve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bourses",
                        to="students.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bourse / Réduction",
                "verbose_name_plural": "Bourses / Réductions",
            },
        ),
        migrations.CreateModel(
            name="FactureFrais",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=150)),
                ("montant_du", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "montant_remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("date_echeance", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("impayee", "Impayée"),
                            ("partielle", "Partiellement payée"),
                            ("payee", "Payée"),
                            ("annulee", "Annulée"),
                        ],
                        default="impayee",
                        max_length=12,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="students.inscription",
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures",
                        to="core.periode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture de frais",
                "verbose_name_plural": "Factures de frais",
                "ordering": ["-date_echeance"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_recu",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("carte", "Carte bancaire"),
                        ],
                        default="especes",
                        max_length=15,
                    ),
                ),
                ("reference_transaction", models.CharField(blank=True, max_length=100)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                (
                    "recu_pdf",
                    models.FileField(blank=True, null=True, upload_to="finance/recus/"),
                ),
                ("annule", models.BooleanField(default=False)),
                (
                    "encaisse_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_encaisses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="finance.facturefrais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="TypeFrais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("unique", "Paiement unique"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="trimestriel",
                        max_length=15,
                    ),
                ),
                ("obligatoire", models.BooleanField(default=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types_frais",
                        to="core.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de frais",
                "verbose_name_plural": "Types de frais",
                "unique_together": {("etablissement", "nom")},
            },
        ),
        migrations.AddField(
            model_name="facturefrais",
            name="type_frais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures",
                to="finance.typefrais",
            ),
        ),
        migrations.CreateModel(
            name="BaremeFrais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baremes_frais",
                        to="core.anneescolaire",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baremes_frais",
                        to="core.niveau",
                    ),
                ),
                (
                    "type_frais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baremes",
                        to="finance.typefrais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barème de frais",
                "verbose_name_plural": "Barèmes de frais",
                "unique_together": {("type_frais", "niveau", "annee_scolaire")},
            },
        ),
    ]
