# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentGenere",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("certificat_scolarite", "Certificat de scolarité"),
                            (
                                "certificat_frequentation",
                                "Certificat de fréquentation scolaire",
                            ),
                            ("convocation_examen", "Convocation - Examen"),
                            ("convocation_reunion", "Convocation - Réunion"),
                            ("attestation_reussite", "Attestation de réussite"),
                            ("attestation_passage", "Attestation de passage"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                ("objet", models.CharField(blank=True, max_length=255)),
                (
                    "contenu_texte",
                    models.TextField(
                        blank=True,
                        help_text="Corps du document (texte brut, une ligne par paragraphe)",
                    ),
                ),
                (
                    "date_evenement",
                    models.DateField(
                        blank=True,
                        help_text="Date de l'examen/réunion pour une convocation",
                        null=True,
                    ),
                ),
                ("lieu_evenement", models.CharField(blank=True, max_length=200)),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/archives/%Y/%m/"
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_generes",
                        to="students.eleve",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_generes",
                        to="staff.employe",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_generes",
                        to="students.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document généré",
                "verbose_name_plural": "Documents générés (archives)",
                "ordering": ["-created_at"],
            },
        ),
    ]
