# Generated by Django 5.2.17 on 2026-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgenere',
            name='type_document',
            field=models.CharField(choices=[('certificat_scolarite', 'Certificat de scolarité'), ('certificat_frequentation', 'Certificat de fréquentation scolaire'), ('convocation_examen', 'Convocation - Examen'), ('convocation_reunion', 'Convocation - Réunion'), ('attestation_reussite', 'Attestation de réussite'), ('attestation_passage', 'Attestation de passage'), ('fiche_permission', 'Fiche de permission'), ('fiche_medicale', 'Fiche médicale'), ('billet_entree', "Billet d'entrée"), ('avis_recouvrement', 'Avis de recouvrement'), ('attestation_travail', 'Attestation de travail'), ('certificat_travail', 'Certificat de travail'), ('certificat_fin_contrat', 'Certificat de fin de contrat'), ('attestation_fin_stage', 'Attestation de fin de stage'), ('fiche_licenciement', 'Fiche de licenciement'), ('autre', 'Autre')], max_length=30),
        ),
    ]
