# Generated by Django 5.2.17 on 2026-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_mgmt', '0002_alter_documentgenere_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgenere',
            name='date_fin_evenement',
            field=models.DateField(blank=True, help_text='Date de fin (permission, stage...), si la période a un terme connu', null=True),
        ),
        migrations.AlterField(
            model_name='documentgenere',
            name='date_evenement',
            field=models.DateField(blank=True, help_text="Date de l'examen/réunion/début de permission ou de stage", null=True),
        ),
        migrations.AlterField(
            model_name='documentgenere',
            name='lieu_evenement',
            field=models.CharField(blank=True, help_text="Lieu, ou provenance (établissement d'origine/spécialité pour un stagiaire)", max_length=200),
        ),
    ]
