# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrateur"),
                            ("admin", "Administrateur d'établissement"),
                            ("enseignant", "Enseignant"),
                            ("eleve", "Élève"),
                            ("parent", "Parent"),
                            ("comptable", "Comptable / Caissier"),
                            ("surveillant", "Surveillant général"),
                        ],
                        default="eleve",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=30)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="users/photos/"),
                ),
                ("doit_changer_mot_de_passe", models.BooleanField(default=False)),
                ("deux_facteurs_actif", models.BooleanField(default=False)),
                ("langue_preferee", models.CharField(default="fr", max_length=5)),
                ("date_derniere_activite", models.DateTimeField(blank=True, null=True)),
                ("est_actif_compte", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="LienParentEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("pere", "Père"),
                            ("mere", "Mère"),
                            ("tuteur", "Tuteur/Tutrice"),
                            ("autre", "Autre"),
                        ],
                        default="tuteur",
                        max_length=10,
                    ),
                ),
                ("est_contact_principal", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Lien parent-élève",
                "verbose_name_plural": "Liens parents-élèves",
            },
        ),
    ]
