# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="etablissement_courant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="etablissements",
            field=models.ManyToManyField(
                blank=True,
                help_text="Établissements auxquels l'utilisateur a accès (multi-établissements)",
                related_name="utilisateurs",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="lienparenteleve",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents_lies",
                to="students.eleve",
            ),
        ),
        migrations.AddField(
            model_name="lienparenteleve",
            name="parent",
            field=models.ForeignKey(
                limit_choices_to={"role": "parent"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enfants_lies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lienparenteleve",
            unique_together={("parent", "eleve")},
        ),
    ]
