# Generated by Django 5.2.17 on 2026-10-05 22:33

import django.db.models.functions.text
from django.db import migrations, models

from apps.core.migration_utils import contrainte_tolerante


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rattacher_comptes_etablissements'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_images_etablissement_en_base'),
    ]

    # Contraintes « tolérantes » : ne bloquent pas le déploiement si la base contient déjà des doublons
    operations = [
        contrainte_tolerante('accounts', 'user', models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='utilisateur_email_unique_insensible_casse')),
        contrainte_tolerante('accounts', 'user', models.UniqueConstraint(condition=models.Q(('telephone', ''), _negated=True), fields=('telephone',), name='utilisateur_telephone_unique')),
    ]
