# Generated by Django 5.2.17 on 2026-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rang", models.PositiveIntegerField(blank=True, null=True)),
                ("effectif_classe", models.PositiveIntegerField(blank=True, null=True)),
                ("appreciation_conseil", models.CharField(blank=True, max_length=255)),
                ("mention", models.CharField(blank=True, max_length=50)),
                (
                    "fichier_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="academique/bulletins/"
                    ),
                ),
                ("genere_le", models.DateTimeField(blank=True, null=True)),
                ("valide", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Bulletin",
                "verbose_name_plural": "Bulletins",
            },
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=150)),
                ("date_examen", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("salle", models.CharField(blank=True, max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Examens",
                "ordering": ["date_examen", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="MoyenneMatiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                ("moyenne", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rang", models.PositiveIntegerField(blank=True, null=True)),
                ("appreciation", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Moyenne par matière",
                "verbose_name_plural": "Moyennes par matière",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "bareme",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("date_evaluation", models.DateField(blank=True, null=True)),
                ("observation", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-periode", "matiere"],
            },
        ),
        migrations.CreateModel(
            name="TableauHonneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("honneur", "Tableau d'honneur"),
                            ("excellence", "Tableau d'excellence"),
                        ],
                        default="honneur",
                        max_length=12,
                    ),
                ),
                ("moyenne", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rang_classe", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Tableau d'honneur/excellence",
                "verbose_name_plural": "Tableaux d'honneur/excellence",
            },
        ),
        migrations.CreateModel(
            name="TypeEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=60)),
                (
                    "ponderation",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Poids relatif dans la moyenne de la matière",
                        max_digits=4,
                    ),
                ),
            ],
        ),
    ]
