# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0001_initial"),
        ("staff", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulletins",
                to="students.inscription",
            ),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulletins",
                to="core.periode",
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examens",
                to="core.classe",
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examens",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examens",
                to="core.matiere",
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examens",
                to="core.periode",
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="surveillants",
            field=models.ManyToManyField(
                blank=True, related_name="examens_surveilles", to="staff.enseignant"
            ),
        ),
        migrations.AddField(
            model_name="moyennematiere",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moyennes_matieres",
                to="students.inscription",
            ),
        ),
        migrations.AddField(
            model_name="moyennematiere",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moyennes",
                to="core.matiere",
            ),
        ),
        migrations.AddField(
            model_name="moyennematiere",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moyennes_matieres",
                to="core.periode",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes_saisies",
                to="staff.enseignant",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="students.inscription",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.matiere",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.periode",
            ),
        ),
        migrations.AddField(
            model_name="tableauhonneur",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tableaux_honneur",
                to="students.inscription",
            ),
        ),
        migrations.AddField(
            model_name="tableauhonneur",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tableaux_honneur",
                to="core.periode",
            ),
        ),
        migrations.AddField(
            model_name="typeevaluation",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types_evaluation",
                to="core.etablissement",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="type_evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="academics.typeevaluation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bulletin",
            unique_together={("inscription", "periode")},
        ),
        migrations.AlterUniqueTogether(
            name="moyennematiere",
            unique_together={("inscription", "matiere", "periode")},
        ),
        migrations.AlterUniqueTogether(
            name="tableauhonneur",
            unique_together={("inscription", "periode")},
        ),
        migrations.AlterUniqueTogether(
            name="typeevaluation",
            unique_together={("etablissement", "nom")},
        ),
    ]
