# Generated by Django 5.2.17 on 2026-10-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0005_etablissement_cap'),
        ('staff', '0001_initial'),
        ('students', '0002_eleve_nom_mere_eleve_nom_pere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeevaluation',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.AddField(
            model_name='typeevaluation',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage des colonnes dans le carnet de notes"),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=100)),
                ('date_evaluation', models.DateField(blank=True, null=True)),
                ('bareme', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='staff.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.periode')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='academics.typeevaluation')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['type_evaluation__ordre', 'date_evaluation', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.evaluation'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluation__isnull', False)), fields=('evaluation', 'inscription'), name='note_unique_par_evaluation'),
        ),
    ]
