# Generated by Django 5.2.17 on 2026-09-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Eleve",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(blank=True, max_length=30, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(blank=True, max_length=100)),
                ("nationalite", models.CharField(default="Malienne", max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="eleves/photos/"
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("groupe_sanguin", models.CharField(blank=True, max_length=5)),
                ("allergies_ou_besoins_speciaux", models.TextField(blank=True)),
                ("contact_urgence_nom", models.CharField(blank=True, max_length=150)),
                (
                    "contact_urgence_telephone",
                    models.CharField(blank=True, max_length=30),
                ),
                ("ecole_provenance", models.CharField(blank=True, max_length=150)),
                ("actif", models.BooleanField(default=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eleves",
                        to="core.etablissement",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profil_eleve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_inscription",
                    models.CharField(
                        choices=[
                            ("inscription", "Nouvelle inscription"),
                            ("reinscription", "Réinscription"),
                        ],
                        default="inscription",
                        max_length=15,
                    ),
                ),
                ("date_inscription", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("transferee", "Transférée"),
                            ("abandonnee", "Abandonnée"),
                            ("terminee", "Terminée / Promue"),
                            ("exclue", "Exclue"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("redoublant", models.BooleanField(default=False)),
                ("boursier", models.BooleanField(default=False)),
                ("observations", models.TextField(blank=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="core.anneescolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="core.classe",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="students.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-date_inscription"],
                "unique_together": {("eleve", "annee_scolaire")},
            },
        ),
        migrations.CreateModel(
            name="CarteScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "numero_carte",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("date_expiration", models.DateField(blank=True, null=True)),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, null=True, upload_to="eleves/cartes/"),
                ),
                ("qr_code_data", models.CharField(blank=True, max_length=255)),
                (
                    "inscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carte_scolaire",
                        to="students.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carte scolaire",
                "verbose_name_plural": "Cartes scolaires",
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[("absence", "Absence"), ("retard", "Retard")],
                        default="absence",
                        max_length=10,
                    ),
                ),
                (
                    "duree_minutes_retard",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("justifiee", models.BooleanField(default=False)),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "piece_justificative",
                    models.FileField(
                        blank=True, null=True, upload_to="eleves/justificatifs/"
                    ),
                ),
                (
                    "creneau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absences",
                        to="core.creneauemploidutemps",
                    ),
                ),
                (
                    "signale_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="students.inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence / Retard",
                "verbose_name_plural": "Absences / Retards",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SanctionRecompense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("sanction", "Sanction"),
                            ("recompense", "Récompense"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "type_sanction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("avertissement", "Avertissement"),
                            ("blame", "Blâme"),
                            ("exclusion_temporaire", "Exclusion temporaire"),
                            ("exclusion_definitive", "Exclusion définitive"),
                            ("travail_interet_general", "Travail d'intérêt général"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "type_recompense",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tableau_honneur", "Tableau d'honneur"),
                            ("tableau_excellence", "Tableau d'excellence"),
                            ("felicitations", "Félicitations"),
                            ("encouragements", "Encouragements"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("motif", models.TextField()),
                (
                    "decidee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions_recompenses",
                        to="students.inscription",
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions_recompenses",
                        to="core.periode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sanction / Récompense",
                "verbose_name_plural": "Sanctions / Récompenses",
                "ordering": ["-date"],
            },
        ),
    ]
