# Generated by Django 5.2.17 on 2026-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='nom_mere',
            field=models.CharField(blank=True, help_text='Nom de la mère (figure sur les certificats officiels)', max_length=150),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_pere',
            field=models.CharField(blank=True, help_text='Nom du père (figure sur les certificats officiels)', max_length=150),
        ),
    ]
