# Generated by Django 5.2.17 on 2026-10-05 22:33

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from apps.core.migration_utils import contrainte_tolerante


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_images_etablissement_en_base'),
        ('students', '0002_eleve_nom_mere_eleve_nom_pere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Contraintes « tolérantes » : ne bloquent pas le déploiement si la base contient déjà des doublons
    operations = [
        contrainte_tolerante('students', 'eleve', models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), django.db.models.functions.text.Lower('prenom'), models.F('date_naissance'), models.F('etablissement'), name='eleve_unique_par_etablissement')),
    ]
